# Generated by Django 3.0.4 on 2020-03-31 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Callback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('vacancy', models.CharField(blank=True, max_length=20, verbose_name='Когда позвонить')),
            ],
            options={
                'verbose_name': 'Запрос на обратную связь',
                'verbose_name_plural': 'Запросы на обратную связь',
            },
        ),
    ]
