# Generated by Django 3.0.4 on 2020-03-31 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callback', '0002_auto_20200331_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callback',
            name='email',
            field=models.CharField(blank=True, max_length=55, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='callback',
            name='vacancy',
            field=models.CharField(blank=True, max_length=50, verbose_name='Вакансия'),
        ),
    ]
