# Generated by Django 3.0.4 on 2020-03-31 10:39

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20200330_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('picture_card', models.ImageField(default=None, upload_to='', verbose_name='Фото карточки')),
                ('picture_article', models.ImageField(default=None, upload_to='', verbose_name='Фото заголовка статьи')),
                ('subtitle', models.TextField(verbose_name='Подзаголовок статьи')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст статьи')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Сортировать')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
                'ordering': ['order'],
            },
        ),
    ]
