# Generated by Django 3.0.4 on 2020-03-31 11:03

import autoslug.fields
import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['order'], 'verbose_name': 'Продукция', 'verbose_name_plural': 'Продукция'},
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update='True', default='kinda default one', editable=False, max_length=220, populate_from='title', unique='True'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='picture_article',
            field=models.ImageField(default=None, upload_to=base.models.Product.get_image_path, verbose_name='Фото заголовка статьи'),
        ),
        migrations.AlterField(
            model_name='product',
            name='picture_card',
            field=models.ImageField(default=None, upload_to=base.models.Product.get_image_path, verbose_name='Фото карточки'),
        ),
    ]
