# Generated by Django 3.0.4 on 2020-04-01 05:29

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_indexpageslide'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexPageFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='Текст')),
                ('picture', models.ImageField(default=None, upload_to=base.models.IndexPageFeature.get_image_path, verbose_name='Фото')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Сортировать')),
            ],
            options={
                'verbose_name': 'Преимущество на главной странице',
                'verbose_name_plural': 'Преимущества на главной странице',
                'ordering': ['order'],
            },
        ),
    ]
