# Generated by Django 3.0.4 on 2020-04-02 07:20

import base.models
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_indexpagefeature'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(default=None, upload_to=base.models.AboutPageImg.get_image_path, verbose_name='Фото')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Сортировать')),
            ],
            options={
                'verbose_name': 'Логотип компании',
                'verbose_name_plural': 'Логотипы компании',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AboutPageText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст')),
            ],
        ),
    ]
