# Generated by Django 3.0.4 on 2020-04-02 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_aboutpageimg_aboutpagetext'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpageimg',
            options={'ordering': ['order'], 'verbose_name': 'Свойство', 'verbose_name_plural': 'Свойства'},
        ),
        migrations.AlterModelOptions(
            name='aboutpagetext',
            options={'ordering': ['order'], 'verbose_name': 'Видео', 'verbose_name_plural': 'Видео'},
        ),
        migrations.AddField(
            model_name='aboutpageimg',
            name='about_page_text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.AboutPageText'),
        ),
        migrations.AddField(
            model_name='aboutpagetext',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Сортировать'),
        ),
    ]
