# Generated by Django 3.0.4 on 2020-04-18 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20200402_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='coordinates_center',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Коорд-ты центра'),
        ),
        migrations.AddField(
            model_name='contact',
            name='coordinates_center_mobile',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Коорд-ты центра в моб. версии'),
        ),
        migrations.AddField(
            model_name='contact',
            name='coordinates_placemark',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Коорд-ты метки'),
        ),
    ]
