# Generated by Django 3.0.4 on 2020-04-18 06:43

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20200418_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfidentialityAndTerms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidentiality', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Политика конфиденциальности')),
                ('terms', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Пользовательское соглашение')),
            ],
            options={
                'verbose_name': 'Конфиденциальность и соглашение',
                'verbose_name_plural': 'Конфиденциальность и соглашение',
            },
        ),
    ]
