# Generated by Django 3.0.4 on 2020-04-19 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20200419_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpageslide',
            name='link',
            field=models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='Ссылка'),
        ),
    ]
